version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: uptc-db
    environment:
      POSTGRES_USER: uptc_user
      POSTGRES_PASSWORD: uptc_password
      POSTGRES_DB: creditos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: uptc-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://uptc_user:uptc_password@postgres:5432/creditos_db
      JWT_SECRET: tu_clave_secreta_aqui

  frontend:
    build: ./frontend
    container_name: uptc-frontend
    ports:
      - "5173:5173"

volumes:
  postgres_data:
